using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TAOM.Features.CrashReport.Hooks;

namespace TAOM.Tests.Features.CrashReport;

// The native-to-managed callback shims that get a crash-capture Finalizer. Pins each allowlisted
// name against the installed engine's AutoGenerated assemblies (always in the test bin) and keeps
// the list small, because every entry costs a harmony.Patch at boot and a PatchShield attach at
// the first game start.
[TestClass]
public class Native2ManagedTargetsTests
{
    private const string EngineAssembly = "TaleWorlds.Engine.AutoGenerated";
    private const string EngineCallbacks = "ManagedCallbacks.EngineCallbacksGenerated";

    private static readonly Func<string, Assembly?> LoadByName = name =>
    {
        try { return Assembly.Load(name); }
        catch { return null; }
    };

    [TestMethod]
    [TestCategory("BindingVerification")]
    public void All_ResolvesEveryShimAgainstTheInstalledEngine()
    {
        var missing = new List<string>();

        var resolved = Native2ManagedTargets.Resolve(Native2ManagedTargets.All, LoadByName, missing);

        Assert.AreEqual(0, missing.Count, "Callback shims not found in the installed engine: " + string.Join(", ", missing));
        Assert.AreEqual(Native2ManagedTargets.All.Count, resolved.Count);
        foreach (var method in resolved)
        {
            Assert.IsTrue(method.IsStatic, $"{method.DeclaringType?.FullName}.{method.Name} is not static");
            Assert.IsNotNull(method.GetMethodBody(), $"{method.DeclaringType?.FullName}.{method.Name} has no body for Harmony to rewrite");
        }
    }

    [TestMethod]
    public void All_IsExactlyTheSixReviewedShims()
    {
        // Independent of the production list, so emptying or silently swapping an entry fails here.
        // Change this list only together with the entry's stated reason in Native2ManagedTargets.
        var expected = new[]
        {
            $"{EngineAssembly}/{EngineCallbacks}.EngineScreenManager_PreTick",
            $"{EngineAssembly}/{EngineCallbacks}.EngineScreenManager_LateTick",
            $"{EngineAssembly}/{EngineCallbacks}.EngineScreenManager_Update",
            $"{EngineAssembly}/{EngineCallbacks}.ManagedScriptHolder_TickComponents",
            $"{EngineAssembly}/{EngineCallbacks}.ThumbnailCreatorView_OnThumbnailRenderComplete",
            "TaleWorlds.MountAndBlade.AutoGenerated/ManagedCallbacks.CoreCallbacksGenerated.BannerlordTableauManager_RequestCharacterTableauSetup",
        };

        var actual = Native2ManagedTargets.All.Select(t => $"{t.AssemblyName}/{t.TypeName}.{t.MethodName}").ToList();

        CollectionAssert.AreEquivalent(expected, actual);
    }

    [TestMethod]
    public void Resolve_ReportsAMissingMethod_AndSkipsIt()
    {
        var missing = new List<string>();
        var targets = new[] { (EngineAssembly, EngineCallbacks, "NoSuchCallback_Taom006") };

        var resolved = Native2ManagedTargets.Resolve(targets, LoadByName, missing);

        Assert.AreEqual(0, resolved.Count);
        Assert.AreEqual(1, missing.Count);
        StringAssert.Contains(missing[0], "NoSuchCallback_Taom006");
    }

    [TestMethod]
    public void Resolve_ReportsAMissingAssembly_AndSkipsIt()
    {
        // A real shim name, so only the assembly lookup can make it missing.
        var missing = new List<string>();
        var targets = new[] { (EngineAssembly, EngineCallbacks, "EngineScreenManager_PreTick") };

        var resolved = Native2ManagedTargets.Resolve(targets, _ => null, missing);

        Assert.AreEqual(0, resolved.Count);
        CollectionAssert.AreEqual(new[] { $"{EngineAssembly}/{EngineCallbacks}.EngineScreenManager_PreTick" }, missing);
    }

    [TestMethod]
    public void Resolve_ReportsAMissingType_AndSkipsIt()
    {
        var missing = new List<string>();
        var targets = new[] { (EngineAssembly, "ManagedCallbacks.NoSuchCallbacksGenerated_Taom006", "EngineScreenManager_PreTick") };

        var resolved = Native2ManagedTargets.Resolve(targets, LoadByName, missing);

        Assert.AreEqual(0, resolved.Count);
        Assert.AreEqual(1, missing.Count);
        StringAssert.Contains(missing[0], "NoSuchCallbacksGenerated_Taom006");
    }

    [TestMethod]
    public void Resolve_ReportsALookupThatThrows_AndKeepsGoing()
    {
        // GetMethod by name throws AmbiguousMatchException on an overloaded name; the entry is
        // reported missing and the next entry still resolves.
        var missing = new List<string>();
        var testAssembly = typeof(Native2ManagedTargetsTests).Assembly;
        var overloaded = typeof(OverloadedCallbacks).FullName!;
        var targets = new[]
        {
            (testAssembly.GetName().Name!, overloaded, nameof(OverloadedCallbacks.Overloaded)),
            (testAssembly.GetName().Name!, overloaded, nameof(OverloadedCallbacks.Single)),
        };

        var resolved = Native2ManagedTargets.Resolve(targets, _ => testAssembly, missing);

        Assert.AreEqual(1, missing.Count);
        StringAssert.Contains(missing[0], nameof(OverloadedCallbacks.Overloaded));
        Assert.AreEqual(1, resolved.Count);
        Assert.AreEqual(nameof(OverloadedCallbacks.Single), resolved[0].Name);
    }

    [TestMethod]
    public void All_IsASmallDistinctAllowlist()
    {
        var all = Native2ManagedTargets.All;

        Assert.AreEqual(all.Count, all.Distinct().Count(), "Native2ManagedTargets.All has a duplicate entry");
        Assert.IsTrue(all.Count <= 12,
            "each entry costs a harmony.Patch at boot plus a PatchShield attach at the first game start (about " +
            "120 to 190 ms each on the maintainer's desktop, under 10 ms on player machines). Add an entry only " +
            "with a stated reason.");
    }

    internal static class OverloadedCallbacks
    {
        internal static void Overloaded() { }
        internal static void Overloaded(int value) { _ = value; }
        internal static void Single() { }
    }
}
