using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TAOM.Features.CrashReport.Hooks;

namespace TAOM.Tests.Features.CrashReport;

// The native-to-managed callback shims that get a crash-capture Finalizer. Pins each allowlisted
// name against the installed engine's AutoGenerated assemblies (always in the test bin) and keeps
// the list small, because every entry is one harmony.Patch at boot.
[TestClass]
public class Native2ManagedTargetsTests
{
    private static readonly Func<string, Assembly?> LoadByName = name =>
    {
        try { return Assembly.Load(name); }
        catch { return null; }
    };

    [TestMethod]
    public void All_ResolvesEveryShimAgainstTheInstalledEngine()
    {
        var missing = new List<string>();

        var resolved = Native2ManagedTargets.Resolve(Native2ManagedTargets.All, LoadByName, missing);

        Assert.AreEqual(0, missing.Count, "Callback shims not found in the installed engine: " + string.Join(", ", missing));
        Assert.AreEqual(Native2ManagedTargets.All.Count, resolved.Count);
        foreach (var method in resolved)
        {
            Assert.IsTrue(method.IsStatic, $"{method.DeclaringType?.FullName}.{method.Name} is not static");
            Assert.IsNotNull(method.GetMethodBody(), $"{method.DeclaringType?.FullName}.{method.Name} has no body for Harmony to rewrite");
        }
    }

    [TestMethod]
    public void Resolve_ReportsAMissingMethod_AndSkipsIt()
    {
        var missing = new List<string>();
        var targets = new[] { ("TaleWorlds.Engine.AutoGenerated", "ManagedCallbacks.EngineCallbacksGenerated", "NoSuchCallback_Taom006") };

        var resolved = Native2ManagedTargets.Resolve(targets, LoadByName, missing);

        Assert.AreEqual(0, resolved.Count);
        Assert.AreEqual(1, missing.Count);
        StringAssert.Contains(missing[0], "NoSuchCallback_Taom006");
    }

    [TestMethod]
    public void Resolve_ReportsAMissingAssembly_AndSkipsIt()
    {
        var missing = new List<string>();
        var targets = new[] { ("TaleWorlds.Engine.AutoGenerated", "ManagedCallbacks.EngineCallbacksGenerated", "NoSuchCallback_Taom006") };

        var resolved = Native2ManagedTargets.Resolve(targets, _ => null, missing);

        Assert.AreEqual(0, resolved.Count);
        Assert.AreEqual(1, missing.Count);
        StringAssert.Contains(missing[0], "TaleWorlds.Engine.AutoGenerated");
    }

    [TestMethod]
    public void All_IsASmallDistinctAllowlist()
    {
        var all = Native2ManagedTargets.All;

        Assert.AreEqual(all.Count, all.Distinct().Count(), "Native2ManagedTargets.All has a duplicate entry");
        Assert.IsTrue(all.Count <= 12,
            "each entry is one harmony.Patch at boot (about 120 to 190 ms on the maintainer's desktop); the " +
            "old 247-method sweep cost 29 to 33 s of every launch. Add an entry only with a stated reason.");
    }
}
