using System;
using System.Threading;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TAOM.Dependencies.Foundation;
using TAOM.Features.CrashReport.Hooks;

namespace TAOM.Tests.Features.CrashReport;

// The callback-shim Finalizer's decision, with the MCM read and the recorded main-thread id factored
// out. No test calls IoC.Configure, so the service is unreachable and HandleAndSwallow takes its
// hand-back fallback unless a test installs a RecordingCrashService, which pins the swallow path and
// the off-main verdict the service receives.
[TestClass]
public class Native2ManagedBridgeTests
{
    private static int ThisThread => Thread.CurrentThread.ManagedThreadId;

    [TestInitialize]
    public void ClearTheCachedService() => CrashReportPatchHelper.ResetForUnload();

    [TestMethod]
    public void HandleOrPassThrough_WhenCaptureCannotSwallow_HandsBackAnExceptionThatKeepsItsThrowSite()
    {
        // Every non-null return of the bridge is rethrown by Harmony, so every exit must preserve
        // (maintainer decision 2026-09-24, #650). Here capture is on but the service is unreachable.
        var ex = RethrowProbe.CaughtFromTheSite();

        var handedBack = Native2ManagedBridge.HandleOrPassThrough(ex, nativeCaptureEnabled: true, ThisThread);

        Assert.AreSame(ex, handedBack);
        StringAssert.Contains(RethrowProbe.TraceAfterHarmonyRethrow(handedBack!), nameof(RethrowProbe.ThrowAtTheSite),
            "the throw site must survive Harmony's `throw <result>`");
    }

    [TestMethod]
    public void HandleOrPassThrough_WhenNativeCaptureIsOff_HandsBackTheSameExceptionWithItsThrowSite()
    {
        // A thrown exception, so it has live frames: PreserveForRethrow is a no-op on one that
        // never was, and a bare `return exception;` would pass an unthrown fixture unnoticed.
        var ex = ThrowAndCatch();

        var handedBack = Native2ManagedBridge.HandleOrPassThrough(ex, nativeCaptureEnabled: false, ThisThread);

        Assert.AreSame(ex, handedBack);
        Assert.IsTrue(ex.Data.Contains(RethrowStackPreserver.ThrowSiteDataKey),
            "the pass-through must record the throw site before Harmony rethrows (harmony-patches.md)");
    }

    [TestMethod]
    public void HandleOrPassThrough_WithNoException_ReturnsNull()
    {
        Assert.IsNull(Native2ManagedBridge.HandleOrPassThrough(null, nativeCaptureEnabled: true, ThisThread));
        Assert.IsNull(Native2ManagedBridge.HandleOrPassThrough(null, nativeCaptureEnabled: false, ThisThread));
    }

    [TestMethod]
    public void HandleOrPassThrough_WhenNoMainThreadWasRecorded_TellsTheServiceItIsOffMain()
    {
        // 0 is AppDomainExceptionHook.MainThreadId before Subscribe(); managed ids start at 1.
        var service = RecordingCrashService.Install();

        Native2ManagedBridge.HandleOrPassThrough(ThrowAndCatch(), nativeCaptureEnabled: true, mainThreadId: 0);

        Assert.AreEqual(1, service.Calls.Count);
        Assert.IsTrue(service.Calls[0].OffMainThread,
            "with no recorded main thread the bridge cannot prove main-thread delivery, so it takes the safe path");
    }

    [TestMethod]
    public void HandleOrPassThrough_WhenTheServiceCaptures_SwallowsWithTheCallbackOrigin()
    {
        var service = RecordingCrashService.Install();
        var ex = ThrowAndCatch();

        var handedBack = Native2ManagedBridge.HandleOrPassThrough(ex, nativeCaptureEnabled: true, ThisThread);

        Assert.IsNull(handedBack, "a captured exception is swallowed, so native never sees it");
        Assert.AreEqual(1, service.Calls.Count);
        Assert.AreSame(ex, service.Calls[0].Exception);
        Assert.AreEqual("TaleWorlds.AutoGenerated.<callback>", service.Calls[0].Origin);
        Assert.IsFalse(service.Calls[0].OffMainThread, "a capture on the recorded main thread keeps the full sections");
    }

    [TestMethod]
    public void HandleOrPassThrough_CaptureOnAWorkerThread_TellsTheServiceBeforeItCaptures()
    {
        var service = RecordingCrashService.Install();
        var ex = ThrowAndCatch();
        int mainThread = ThisThread;

        RunOnWorkerThread(() => Native2ManagedBridge.HandleOrPassThrough(ex, nativeCaptureEnabled: true, mainThread));

        Assert.AreEqual(1, service.Calls.Count);
        Assert.IsTrue(service.Calls[0].OffMainThread,
            "the service must know the capture is off-main when it runs, or it reads Mission state and shows the inquiry there");
    }

    [TestMethod]
    public void HandleOrPassThrough_CaptureOnAWorkerThread_WithReadOnlyData_StillTellsTheServiceItIsOffMain()
    {
        // Codex 2026-09-24 P2: a best-effort Data write cannot be the only carrier of the decision.
        var service = RecordingCrashService.Install();
        var ex = ThrowAndCatch(new ReadOnlyDataException());
        int mainThread = ThisThread;

        RunOnWorkerThread(() => Native2ManagedBridge.HandleOrPassThrough(ex, nativeCaptureEnabled: true, mainThread));

        Assert.AreEqual(1, service.Calls.Count);
        Assert.IsTrue(service.Calls[0].OffMainThread,
            "an exception whose Data rejects writes must still take the reduced path off the main thread");
    }

    [TestMethod]
    public void HandleOrPassThrough_WhenNativeCaptureIsOff_OnAWorkerThread_NeverReachesTheService()
    {
        var service = RecordingCrashService.Install();
        var ex = ThrowAndCatch();
        int mainThread = ThisThread;
        Exception? handedBack = null;

        RunOnWorkerThread(() => handedBack = Native2ManagedBridge.HandleOrPassThrough(ex, nativeCaptureEnabled: false, mainThread));

        Assert.AreSame(ex, handedBack);
        Assert.AreEqual(0, service.Calls.Count, "with the native toggle off the bridge captures nothing");
    }

    [TestMethod]
    public void Finalizer_ComparesAgainstTheIdTheHookRecorded()
    {
        // Pins the wiring from Finalizer to AppDomainExceptionHook.MainThreadId: passing any other
        // id (0, say) would send every capture down the reduced path.
        var hook = new AppDomainExceptionHook(new RecordingCrashService(), NSubstitute.Substitute.For<TAOM.Core.Logging.IModLogger>());
        try
        {
            hook.Subscribe();
            var service = RecordingCrashService.Install();

            Assert.IsNull(Native2ManagedBridge.Finalizer(ThrowAndCatch()));

            Assert.AreEqual(1, service.Calls.Count);
            Assert.IsFalse(service.Calls[0].OffMainThread, "the subscribing thread is the main thread");
        }
        finally
        {
            hook.Unsubscribe();
        }
    }

    [TestMethod]
    public void Finalizer_OnTheSuccessPath_ReturnsNull()
    {
        // Harmony calls the finalizer on every successful call with a null __exception; this is
        // the only path that runs in normal play.
        Assert.IsNull(Native2ManagedBridge.Finalizer(null));
    }

    [TestCleanup]
    public void DropTheInstalledService() => CrashReportPatchHelper.ResetForUnload();

    private static InvalidOperationException ThrowAndCatch() => ThrowAndCatch(new InvalidOperationException("taom-006"));

    private static T ThrowAndCatch<T>(T exception) where T : Exception
    {
        try { throw exception; }
        catch (T caught) { return caught; }
    }

    private static void RunOnWorkerThread(Action action)
    {
        Exception? failure = null;
        var worker = new Thread(() =>
        {
            try { action(); }
            catch (Exception ex) { failure = ex; }
        });
        worker.Start();
        worker.Join();
        if (failure != null) throw new AssertFailedException("the worker thread threw: " + failure);
    }
}
