"""
Generate Bannerlord material tpacs (t_rivendell_*_mtl.tpac) by cloning a
hand-authored template material and substituting name + texture GUIDs.

Format (mapped 2026-07-15 from the user's hand-made materials; container
layout matches tools/tpac_skeleton_inject.py):
  header:  TPAC magic | ver=2 | package guid (16) | item count | toc size (8)
  item:    type guid (16, Material=9313b01d...) | item guid (16) | ver (4)
           | name len+bytes | meta len (8) + meta | checksum (8) | segc=0 | ud=0
  meta:    flags/floats constant per shader config; three 16-byte texture GUID
           slots (diffuse/normal/specular) — each the item guid of the bound
           <texture>_tex.tpac. Located by searching for the template's own GUIDs.

CHECKSUM CAVEAT: algorithm unknown (9 algos x 7 slices swept, no match across
22 known pairs) — the template's checksum is COPIED verbatim. Empirically
validated in the Modding Kit before batch use; if the editor ever starts
rejecting these, re-open the checksum question.

Never overwrites an existing _mtl.tpac by default. --force re-writes ONLY
files this script itself generated (tracked in _generated_manifest.json in
the textures dir) — hand-made materials are never touched, enforced in code.

Usage:
    python tools/oneoff/generate_rivendell_materials.py --only t_rivendell_dining_set   # pilot
    python tools/oneoff/generate_rivendell_materials.py --all
"""

from __future__ import annotations

import argparse
import csv
import struct
import sys
import uuid
from pathlib import Path

TEX_DIR = Path(r"E:/Steam/steamapps/common/Mount & Blade II Bannerlord/Modules/TAOM_Map/Assets/Scenes/rivendell/textures")
SHEET = Path(r"E:/LOTRAOMAssets/_export/rivendell/material_sheet.csv")
TEMPLATE = TEX_DIR / "t_rivendell_bench_mtl.tpac"
TEMPLATE_SET = "t_rivendell_bench"  # texture set the template binds


def parse_mtl(path: Path):
    d = path.read_bytes()
    assert d[0:4] == b"TPAC", path
    pos = 36
    tg = d[pos:pos+16]; pos += 16
    pos += 16 + 4  # item guid + item version
    n = struct.unpack_from("<i", d, pos)[0]; pos += 4 + n
    ml = struct.unpack_from("<q", d, pos)[0]; pos += 8
    meta = d[pos:pos+ml]; pos += ml
    checksum = d[pos:pos+8]; pos += 8
    tail = d[pos:]  # seg count + user data (0,0)
    return dict(type_guid=tg, meta=bytearray(meta), checksum=checksum, tail=tail,
                version_field=d[36+32:36+36])


def tex_item_guid(set_stem: str, role: str) -> bytes | None:
    p = TEX_DIR / f"{set_stem}_{role}_tex.tpac"
    if not p.is_file():
        return None
    d = p.read_bytes()
    return d[36+16:36+32]


def build(name: str, meta: bytes, tpl) -> bytes:
    name_b = name.encode()
    item = (tpl["type_guid"] + uuid.uuid4().bytes + tpl["version_field"]
            + struct.pack("<i", len(name_b)) + name_b
            + struct.pack("<q", len(meta)) + meta
            + tpl["checksum"] + tpl["tail"])
    header = (b"TPAC" + struct.pack("<I", 2) + uuid.uuid4().bytes
              + struct.pack("<I", 1) + struct.pack("<Q", len(item)))
    return header + item


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--only", help="generate just this material (pilot)")
    g.add_argument("--all", action="store_true")
    ap.add_argument("--force", action="store_true",
                    help="overwrite files previously generated by this script (per _generated_manifest.json); hand-made files are never overwritten")
    args = ap.parse_args()

    manifest_path = TEX_DIR / "_generated_manifest.json"
    generated: set[str] = set(json.loads(manifest_path.read_text())) if manifest_path.is_file() else set()

    tpl = parse_mtl(TEMPLATE)
    tpl_guids = {}
    for role in ("d", "n", "s"):
        g16 = tex_item_guid(TEMPLATE_SET, role)
        off = tpl["meta"].find(g16) if g16 else -1
        if off < 0:
            sys.exit(f"template does not bind {TEMPLATE_SET}_{role} — pick another template")
        tpl_guids[role] = off
    print(f"[gen] template {TEMPLATE.name}: guid slots d@{tpl_guids['d']} n@{tpl_guids['n']} s@{tpl_guids['s']}")

    rows = list(csv.DictReader(open(SHEET, encoding="utf-8")))
    made = skipped_exists = skipped_incomplete = 0
    for r in rows:
        name = r["material"]
        if args.only and name != args.only:
            continue
        if not r["tex_d"]:
            continue  # manual-only material
        out = TEX_DIR / f"{name}_mtl.tpac"
        if out.exists() and not (args.force and name in generated):
            skipped_exists += 1
            continue
        base_stem = name
        for suffix in ("_foliage", "_translucent"):
            if base_stem.endswith(suffix):
                base_stem = base_stem[:-len(suffix)]
        guids = {}
        for role in ("d", "n", "s"):
            ref = r[f"tex_{role}"]
            if ref.startswith("MISSING:"):
                ref = ""  # sheet flagged the texture absent — treat as no ref
            guids[role] = tex_item_guid(ref[:-6], role) if ref else None
            if guids[role] is None:
                # Sheet ref empty (UE master bound no such param) but a
                # same-named imported texture exists — bind by convention.
                guids[role] = tex_item_guid(base_stem, role)
        if any(v is None for v in guids.values()):
            skipped_incomplete += 1
            print(f"[gen] SKIP {name}: incomplete texture set on disk "
                  f"({[k for k, v in guids.items() if v is None]})")
            continue
        meta = bytearray(tpl["meta"])
        for role, off in tpl_guids.items():
            meta[off:off+16] = guids[role]
        out.write_bytes(build(name, bytes(meta), tpl))
        generated.add(name)
        made += 1
        if args.only:
            print(f"[gen] wrote {out}")

    # Materials meshes demand but no UE texture set exists for — clone the
    # bindings of a stand-in material file. palace_steps' second slot was
    # UE's default WorldGridMaterial; give it the same concrete as slot 1.
    CLONES = {"t_rivendell_worldgridmaterial": "t_rivendell_cs1_baseconcrete_01_4096_b1"}
    if args.all:
        for name, source in CLONES.items():
            out = TEX_DIR / f"{name}_mtl.tpac"
            src = TEX_DIR / f"{source}_mtl.tpac"
            if (out.exists() and not (args.force and name in generated)) or not src.is_file():
                continue
            out.write_bytes(build(name, bytes(parse_mtl(src)["meta"]), tpl))
            generated.add(name)
            made += 1
            print(f"[gen] wrote {out} (clone of {source})")
    manifest_path.write_text(json.dumps(sorted(generated), indent=1))
    print(f"[gen] made={made} skipped_existing={skipped_exists} skipped_incomplete={skipped_incomplete}")


if __name__ == "__main__":
    main()
