#!/usr/bin/env python3
"""One-off: retag the Khand settlement cluster from Easterling (khuzait) to Variag (battania).

TAOM authored `battania` into the Variag culture — `{=TAOM_battania_culture}Variag`, 7.3 KB of
culture XSLT, 26 notable templates, 68 `*_khand` NPCCharacter bindings, a kingdom, 8 clans and 18
TAOM-authored lords — but the K-series settlements were never migrated with it. All 48 stayed `Culture.khuzait`,
so the Variag culture owned nothing while its own clans held 10 fortifications named Sturlurtsa
Khand, Lêrmsakun, Ardîvar and Yanîk Anlî.

Two consequences, one cosmetic and one fatal:

  * Khand produced Easterling notables, volunteer pools, guards and marketplace stock.
  * Vanilla `HeroSpawnCampaignBehavior.SpawnLordParty` ends with an unguarded
    `Settlement.All.First(x => x.Culture == hero.Culture)`, reached when the hero's map faction has
    no `InitialHomeSettlement`. With zero battania settlements that LINQ throws
    `InvalidOperationException` out of `Campaign.Tick` — crash report 099f650c, 2026-08-04.
    Patch65 guards the engine side; this fixes the data that made it reachable.

castle_K4 is deliberately EXCLUDED: it belongs to clan_khuzait_1, a genuine Easterling holding.

TARGET IS THE LIVE FILE. `<game>/Modules/TAOM_Map/ModuleData/settlements.xml` is what the game
reads; the repo's `Main/_Module/ModuleData/settlements.xml` is a stale shadow and editing it
changes nothing (CLAUDE.md Traps).

Save-compat: this applies to EXISTING SAVES, not just new campaigns. `Settlement.Culture` is a bare
`public CultureObject Culture;` (installed v1.4.7 `Settlement.cs:70`) with NO `[SaveableField]`, it
has no entry in `AutoGeneratedSaveManager`'s 28-member Settlement set, and `Settlement.cs:961`
re-reads it from XML on every load. Contrast `Hero.Culture`, also a bare public field, which DOES
get an auto-generated accessor and therefore does persist. TAOM's own CultureConversion feature
re-applies converted cultures on load for exactly this reason. So every player who loads a save
after installing this gets Variag Khand immediately.

Idempotent: settlements already on `Culture.battania` are counted and skipped.

Usage:  python tools/oneoff/retag_khand_to_variag.py [--apply] [--settlements PATH]
        (dry-run by default)
"""
import argparse
import re
import sys
from pathlib import Path

DEFAULT_SETTLEMENTS = Path(
    r"E:\Steam\steamapps\common\Mount & Blade II Bannerlord"
    r"\Modules\TAOM_Map\ModuleData\settlements.xml"
)

FROM_CULTURE = "khuzait"
TO_CULTURE = "battania"

# Explicit allowlist rather than an `id.startswith("town_K")` sweep — a prefix match would also
# take castle_K4 (Easterling) and would silently widen if the map ever gains new K-series ids.
TARGET_IDS = [
    # Towns held by the Variag clans.
    "town_K1", "town_K2", "town_K3", "town_K4",
    # Castles held by the Variag clans (castle_K4 is clan_khuzait_1's — excluded).
    "castle_K1", "castle_K2", "castle_K3", "castle_K5", "castle_K6", "castle_K7",
    # Villages bound to the four Khand towns.
    "village_K1_1", "village_K1_2", "village_K1_3", "village_K1_4",
    "village_K2_1", "village_K2_2", "village_K2_3", "village_K2_4",
    "village_K3_1", "village_K3_2", "village_K3_3", "village_K3_4",
    "village_K4_1", "village_K4_2", "village_K4_3", "village_K4_4",
    # Villages bound to the six retagged CASTLES. Missed on the first pass because the id set was
    # derived from the `village_K*` naming convention instead of from the settlement graph — these
    # are `castle_village_*` and carry `<Components><Village bound="Settlement.castle_KN">`.
    # Leaving them behind split every Khand fief group across two cultures: a battania castle whose
    # villages spawn Easterling headmen (NotablesCampaignBehavior -> settlement.Culture
    # .NotableTemplates) and draw the Easterling villager party template. The village-culture ==
    # bound-parent-culture invariant held 607/607 across the whole map before this migration; the
    # first pass broke it 18 times, and only here.
    # castle_village_K4_* are deliberately EXCLUDED, matching the excluded castle_K4.
    "castle_village_K1_1", "castle_village_K1_2", "castle_village_K1_3",
    "castle_village_K2_1", "castle_village_K2_2", "castle_village_K2_3",
    "castle_village_K3_1", "castle_village_K3_2", "castle_village_K3_3",
    "castle_village_K5_1", "castle_village_K5_2", "castle_village_K5_3",
    "castle_village_K6_1", "castle_village_K6_2", "castle_village_K6_3",
    "castle_village_K7_1", "castle_village_K7_2", "castle_village_K7_3",
]

SETTLEMENT_RE = re.compile(r'<Settlement\b[^>]*?>', re.S)
ID_RE = re.compile(r'\bid="([^"]+)"')
CULTURE_RE = re.compile(r'(\bculture=")Culture\.([^"]+)(")')


def read_text(path: Path):
    """Byte-level read per tools/README.md "XML I/O convention".

    Returns (text, encoding, had_bom). The caller MUST write back with write_bytes — `write_text`
    defaults to `newline=None`, which translates every "\\n" in the string to os.linesep, so on
    Windows a file that already uses CRLF comes back as "\\r\\r\\n" on every line. That is silent
    corruption of a 988-settlement live file: it survives XML parsing, so nothing complains.
    (Caught by deep review 2026-08-04 after the first run of this script did exactly that.)
    """
    raw = path.read_bytes()
    had_bom = raw.startswith(b"\xef\xbb\xbf")
    for encoding in ("utf-8-sig", "utf-16", "utf-8", "cp1252"):
        try:
            return raw.decode(encoding), encoding, had_bom
        except UnicodeDecodeError:
            continue
    raise SystemExit(f"could not decode {path}")


def write_text(path: Path, text: str, had_bom: bool) -> None:
    """Byte-exact write: no newline translation, BOM restored only if it was there."""
    payload = text.encode("utf-8")
    if had_bom and not payload.startswith(b"\xef\xbb\xbf"):
        payload = b"\xef\xbb\xbf" + payload
    path.write_bytes(payload)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--settlements", default=str(DEFAULT_SETTLEMENTS),
                    help="Path to the LIVE TAOM_Map settlements.xml")
    ap.add_argument("--apply", action="store_true",
                    help="Write the file (default is a dry run)")
    args = ap.parse_args()

    path = Path(args.settlements)
    if not path.exists():
        print(f"FAIL: settlements file not found: {path}")
        print("      Pass --settlements if the game install moved.")
        return 1

    text, encoding, had_bom = read_text(path)
    targets = set(TARGET_IDS)
    retagged, already, wrong_source, seen = [], [], [], set()
    out = []
    cursor = 0

    for m in SETTLEMENT_RE.finditer(text):
        tag = m.group(0)
        idm = ID_RE.search(tag)
        if not idm or idm.group(1) not in targets:
            continue
        sid = idm.group(1)
        seen.add(sid)

        cm = CULTURE_RE.search(tag)
        if not cm:
            wrong_source.append((sid, "(no culture attribute)"))
            continue
        current = cm.group(2)
        if current == TO_CULTURE:
            already.append(sid)
            continue
        if current != FROM_CULTURE:
            # Guard: only ever convert away from the culture this migration is about.
            wrong_source.append((sid, current))
            continue

        new_tag = tag[:cm.start()] + f'{cm.group(1)}Culture.{TO_CULTURE}{cm.group(3)}' + tag[cm.end():]
        out.append(text[cursor:m.start()])
        out.append(new_tag)
        cursor = m.end()
        retagged.append(sid)

    out.append(text[cursor:])
    missing = sorted(targets - seen)

    print(f"file:      {path}  (encoding {encoding}, BOM {had_bom})")
    print(f"retag:     Culture.{FROM_CULTURE} -> Culture.{TO_CULTURE}")
    print(f"targets:   {len(TARGET_IDS)}")
    print(f"to change: {len(retagged)}   already {TO_CULTURE}: {len(already)}")
    if retagged:
        print("           " + ", ".join(retagged))
    if wrong_source:
        print(f"SKIPPED (unexpected source culture): {len(wrong_source)}")
        for sid, cul in wrong_source:
            print(f"           {sid}: {cul}")
    if missing:
        print(f"MISSING from the settlement file: {len(missing)}")
        for sid in missing:
            print(f"           {sid}")

    if wrong_source or missing:
        print("\nFAIL: refusing to write - the map does not match this migration's assumptions.")
        return 1

    if not retagged:
        print("\nnothing to do (already migrated)")
        return 0

    if not args.apply:
        print("\ndry run - re-run with --apply to write")
        return 0

    backup = path.with_suffix(path.suffix + ".bak_khand_culture")
    if not backup.exists():
        backup.write_bytes(path.read_bytes())
        print(f"\nbackup:    {backup}")
    write_text(path, "".join(out), had_bom)
    print(f"WROTE:     {len(retagged)} settlements retagged to Culture.{TO_CULTURE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
