using MCM.Abstractions.Attributes;
using MCM.Abstractions.Attributes.v2;
using MCM.Abstractions.Base.Global;

namespace TAOM.Features.CrashReport;

// Dedicated CrashReport MCM page. Default values match the "comprehensive capture"
// posture — every signal is on by default; players who hit perf issues can disable
// specific sections.
public sealed class CrashReportSettings : AttributeGlobalSettings<CrashReportSettings>
{
    public override string Id => "TAOM.CrashReport";
    public override string DisplayName => "TAOM — Crash Report";
    public override string FolderName => "TAOM";
    public override string FormatType => "json2";

    // --- Master ---

    [SettingPropertyGroup("Master")]
    [SettingPropertyBool("Enable Crash Capture", Order = 0,
        HintText = "Master toggle. When off, all Harmony Finalizers no-op and AppDomain hook unsubscribes.")]
    public bool EnableCrashCapture { get; set; } = true;

    [SettingPropertyGroup("Master")]
    [SettingPropertyBool("Suspend BUTR Exception Handler", Order = 1,
        HintText = "On first capture, calls ButterLib.ExceptionHandlerSubSystem.Disable() so TAOM's report wins. Default ON.")]
    public bool SuspendButterLibHandler { get; set; } = true;

    [SettingPropertyGroup("Master")]
    [SettingPropertyBool("Enable Native-to-Managed Capture", Order = 2,
        HintText = "Patches every static method in TaleWorlds.*.AutoGenerated.dll *CallbacksGenerated types — catches exceptions from native callback shims. Finalizers cost zero unless an exception throws. Default ON.")]
    public bool EnableNativeToManagedCapture { get; set; } = true;

    // --- Bundle ---

    [SettingPropertyGroup("Bundle")]
    [SettingPropertyBool("Write Crash Bundle ZIP", Order = 0,
        HintText = "Produces Logs/taom_crash_<timestamp>_<sig>.zip containing report.txt, report.json, taom_debug.log, rgl_log.txt, manifest.txt. Default ON.")]
    public bool WriteCrashBundle { get; set; } = true;

    // --- QA ---

    [SettingPropertyGroup("QA — Dev Triggers")]
    [SettingPropertyBool("Throw On Next Mission Tick", Order = 0,
        HintText = "QA only. Throws a tagged TaomDevTriggerException on the next Mission.Tick to exercise the crash capture pipeline. Auto-resets to OFF after firing.")]
    public bool ThrowOnNextMissionTick { get; set; }

    [SettingPropertyGroup("QA — Dev Triggers")]
    [SettingPropertyBool("Throw On Next Application Tick", Order = 1,
        HintText = "QA only. Throws a tagged TaomDevTriggerException on the next Module.OnApplicationTick to exercise the capture pipeline without entering a mission. Auto-resets to OFF after firing.")]
    public bool ThrowOnNextApplicationTick { get; set; }
}
