using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using HarmonyLib;
using TAOM.Core.Logging;

namespace TAOM.Features.CrashReport.Hooks;

// Attaches the crash-capture Finalizer to the native-to-managed callback shims listed in
// Native2ManagedTargets (an allowlist; see the cost note there). Harmony runs a Finalizer on
// every call of its target with a null __exception when nothing threw, so the steady-state
// cost is small but not zero. The MCM toggle EnableNativeToManagedCapture is read by
// Native2ManagedBridge when an exception arrives, so it works live without a restart.
public sealed class Native2ManagedPatcher
{
    private readonly IModLogger _logger;
    private bool _attached;

    public Native2ManagedPatcher(IModLogger logger)
    {
        _logger = logger;
    }

    public int AttachAll(Harmony harmony)
    {
        if (_attached) return 0;
        _attached = true;
        var stopwatch = Stopwatch.StartNew();

        // We can't use HandleAndSwallow directly as a Harmony Finalizer because it
        // takes (Exception, string). Wrap with a dedicated bridge method.
        var bridge = typeof(Native2ManagedBridge).GetMethod(
            "Finalizer",
            BindingFlags.NonPublic | BindingFlags.Static);
        if (bridge == null)
        {
            _logger.LogError("[CrashReport] Native2Managed: bridge Finalizer missing, skip");
            return 0;
        }

        var missing = new List<string>();
        var targets = Native2ManagedTargets.Resolve(Native2ManagedTargets.All, TryFindAssembly, missing);
        foreach (var name in missing)
            _logger.LogWarning($"[CrashReport] Native2Managed: target not found, skipped: {name}");

        int patched = 0;
        foreach (var m in targets)
        {
            try
            {
                harmony.Patch(m, finalizer: new HarmonyMethod(bridge));
                patched++;
            }
            catch (Exception ex)
            {
                _logger.LogWarning($"[CrashReport] Native2Managed: skip {m.DeclaringType?.FullName}.{m.Name}: {ex.GetType().Name}");
            }
        }
        _logger.LogInfo($"[CrashReport] Native2Managed: attached {patched} of {Native2ManagedTargets.All.Count} Finalizer(s) in {stopwatch.ElapsedMilliseconds} ms");
        return patched;
    }

    private static Assembly? TryFindAssembly(string simpleName)
    {
        try
        {
            return AppDomain.CurrentDomain.GetAssemblies()
                .FirstOrDefault(a => string.Equals(a.GetName().Name, simpleName, StringComparison.Ordinal));
        }
        catch { return null; }
    }
}

// Bridge methods so Harmony Finalizers have a `static Exception? Finalizer(Exception __exception)`
// signature without needing a per-target stringly-typed origin.
internal static class Native2ManagedBridge
{
    internal static Exception? Finalizer(Exception __exception)
        => CrashReportPatchHelper.HandleAndSwallow(__exception, "TaleWorlds.AutoGenerated.<callback>");
}
