using System;
using System.Linq;
using System.Reflection;
using HarmonyLib;
using TAOM.Core.Logging;

namespace TAOM.Features.CrashReport.Hooks;

// Reflection-based Finalizer attachment on every static method in any
// *CallbacksGenerated type inside TaleWorlds.{MountAndBlade,Engine,DotNet}.AutoGenerated.dll.
//
// These autogenerated callback shims are the native↔managed boundary the engine
// uses for hot paths. Without a Finalizer here, throws from native callbacks
// land in vanilla's crash handler without our diagnostic surface.
//
// Finalizers cost ~0 unless an exception is thrown — Harmony only invokes them on
// the exception path. The MCM "EnableNativeToManagedCatch" toggle lets us
// disable this branch if perf or compatibility ever becomes an issue.
public sealed class Native2ManagedPatcher
{
    private static readonly string[] AutogenAssemblies =
    {
        "TaleWorlds.MountAndBlade.AutoGenerated",
        "TaleWorlds.Engine.AutoGenerated",
        "TaleWorlds.DotNet.AutoGenerated",
    };

    private readonly IModLogger _logger;
    private bool _attached;

    public Native2ManagedPatcher(IModLogger logger)
    {
        _logger = logger;
    }

    public int AttachAll(Harmony harmony)
    {
        if (_attached) return 0;
        _attached = true;

        var finalizerMethod = typeof(CrashReportPatchHelper).GetMethod(
            nameof(CrashReportPatchHelper.HandleAndSwallow),
            BindingFlags.Public | BindingFlags.Static);
        if (finalizerMethod == null)
        {
            _logger.LogError("[CrashReport] Native2Managed: HandleAndSwallow MethodInfo missing — skip");
            return 0;
        }

        // We can't use HandleAndSwallow directly as a Harmony Finalizer because it
        // takes (Exception, string). Wrap with a dedicated bridge method.
        var bridge = typeof(Native2ManagedBridge).GetMethod(
            "Finalizer",
            BindingFlags.NonPublic | BindingFlags.Static);
        if (bridge == null)
        {
            _logger.LogError("[CrashReport] Native2Managed: bridge Finalizer missing — skip");
            return 0;
        }

        int patched = 0;
        foreach (var asmName in AutogenAssemblies)
        {
            var asm = TryFindAssembly(asmName);
            if (asm == null)
            {
                _logger.LogWarning($"[CrashReport] Native2Managed: assembly '{asmName}' not loaded — skip");
                continue;
            }
            try
            {
                var types = SafeGetTypes(asm).Where(t => t != null && t.Name.EndsWith("CallbacksGenerated", StringComparison.Ordinal));
                foreach (var t in types)
                {
                    var methods = t.GetMethods(BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public);
                    foreach (var m in methods)
                    {
                        try
                        {
                            harmony.Patch(m, finalizer: new HarmonyMethod(bridge));
                            patched++;
                        }
                        catch (Exception ex)
                        {
                            _logger.LogWarning($"[CrashReport] Native2Managed: skip {t.FullName}.{m.Name}: {ex.GetType().Name}");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning($"[CrashReport] Native2Managed: enum failed for {asmName}: {ex.GetType().Name}: {ex.Message}");
            }
        }
        _logger.LogInfo($"[CrashReport] Native2Managed: attached {patched} Finalizer(s)");
        return patched;
    }

    private static Assembly? TryFindAssembly(string simpleName)
    {
        try
        {
            return AppDomain.CurrentDomain.GetAssemblies()
                .FirstOrDefault(a => string.Equals(a.GetName().Name, simpleName, StringComparison.Ordinal));
        }
        catch { return null; }
    }

    private static Type[] SafeGetTypes(Assembly asm)
    {
        try { return asm.GetTypes(); }
        catch (ReflectionTypeLoadException tle) { return tle.Types?.Where(t => t != null).Cast<Type>().ToArray() ?? Array.Empty<Type>(); }
        catch { return Array.Empty<Type>(); }
    }
}

// Bridge methods so Harmony Finalizers have a `static Exception? Finalizer(Exception __exception)`
// signature without needing a per-target stringly-typed origin.
internal static class Native2ManagedBridge
{
    internal static Exception? Finalizer(Exception __exception)
        => CrashReportPatchHelper.HandleAndSwallow(__exception, "TaleWorlds.AutoGenerated.<callback>");
}
