using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using HarmonyLib;
using TAOM.Core.Logging;
using TAOM.Dependencies.Foundation;

namespace TAOM.Features.CrashReport.Hooks;

// Attaches the crash-capture Finalizer to the native-to-managed callback shims listed in
// Native2ManagedTargets (an allowlist; see the cost note there). Harmony runs a Finalizer on
// every call of its target with a null __exception when nothing threw, so the steady-state
// cost is small but not zero. The MCM toggle EnableNativeToManagedCapture is read by
// Native2ManagedBridge when an exception arrives, so it works live without a restart.
public sealed class Native2ManagedPatcher
{
    private readonly IModLogger _logger;
    private bool _attached;

    public Native2ManagedPatcher(IModLogger logger)
    {
        _logger = logger;
    }

    public int AttachAll(Harmony harmony)
    {
        if (_attached) return 0;
        _attached = true;
        var stopwatch = Stopwatch.StartNew();

        var missing = new List<string>();
        var targets = Native2ManagedTargets.Resolve(Native2ManagedTargets.All, TryFindAssembly, missing);
        foreach (var name in missing)
            _logger.LogWarning($"[CrashReport] Native2Managed: target not found, skipped: {name}");

        int patched = 0;
        foreach (var m in targets)
        {
            try
            {
                // HandleAndSwallow takes (Exception, string), so it cannot be the Finalizer itself;
                // the bridge wraps it. nameof makes a rename a build error, not a silent no-attach.
                harmony.Patch(m, finalizer: new HarmonyMethod(
                    typeof(Native2ManagedBridge), nameof(Native2ManagedBridge.Finalizer)));
                patched++;
            }
            catch (Exception ex)
            {
                _logger.LogWarning($"[CrashReport] Native2Managed: skip {m.DeclaringType?.FullName}.{m.Name}: {ex.GetType().Name}");
            }
        }
        _logger.LogInfo($"[CrashReport] Native2Managed: attached {patched} of {Native2ManagedTargets.All.Count} Finalizer(s) in {stopwatch.ElapsedMilliseconds} ms");
        return patched;
    }

    private static Assembly? TryFindAssembly(string simpleName)
    {
        try
        {
            return AppDomain.CurrentDomain.GetAssemblies()
                .FirstOrDefault(a => string.Equals(a.GetName().Name, simpleName, StringComparison.Ordinal));
        }
        catch { return null; }
    }
}

// Harmony Finalizer for the allowlisted callback shims. Reads the MCM toggle only when an
// exception is on the wire, so the per-call cost of the null path stays one comparison.
internal static class Native2ManagedBridge
{
    private const string Origin = "TaleWorlds.AutoGenerated.<callback>";

    internal static Exception? Finalizer(Exception? __exception)
    {
        if (__exception == null) return null;
        bool enabled = true;
        try { enabled = CrashReportSettings.Instance?.EnableNativeToManagedCapture ?? true; }
        catch { /* a settings read failure must not change the capture path */ }
        return HandleOrPassThrough(__exception, enabled);
    }

    internal static Exception? HandleOrPassThrough(Exception? exception, bool nativeCaptureEnabled)
    {
        if (exception == null) return null;
        if (!nativeCaptureEnabled)
            return RethrowStackPreserver.PreserveForRethrow(exception, null);
        return CrashReportPatchHelper.HandleAndSwallow(exception, Origin);
    }
}
