using System;
using System.Collections.Generic;
using System.Reflection;

namespace TAOM.Features.CrashReport.Hooks;

// The native-to-managed callback shims that get a crash-capture Finalizer. An allowlist, not a
// sweep. Patching every static method of every *CallbacksGenerated type (247) captured nothing
// in 30 logged sessions. Each entry costs one harmony.Patch at boot plus one PatchShield attach
// at the first game start (pass 2 shields every patched method not declared in a TAOM assembly,
// outside its namespace exclusions).
// On the maintainer's desktop each attach took about 120 to 190 ms (2026-09-23 logs), so the
// sweep cost 29 to 33 s of every launch there; on 11 player processes it took 0 to 1 s in all
// (plans/_audit/2026-09-23-opus/followup-patch-tax.md).
//
// An entry earns its place by covering managed code that no Patch37 finalizer already wraps.
// Names are pinned against the installed engine by Native2ManagedTargetsTests.
public static class Native2ManagedTargets
{
    private const string EngineAssembly = "TaleWorlds.Engine.AutoGenerated";
    private const string EngineCallbacks = "ManagedCallbacks.EngineCallbacksGenerated";
    private const string CoreAssembly = "TaleWorlds.MountAndBlade.AutoGenerated";
    private const string CoreCallbacks = "ManagedCallbacks.CoreCallbacksGenerated";

    public static readonly IReadOnlyList<(string AssemblyName, string TypeName, string MethodName)> All = new[]
    {
        // ScreenManager.EarlyUpdate: no Patch37 finalizer wraps it.
        (EngineAssembly, EngineCallbacks, "EngineScreenManager_PreTick"),
        // ScreenManager.LateTick: every screen layer's RenderTick.
        (EngineAssembly, EngineCallbacks, "EngineScreenManager_LateTick"),
        // ScreenManager.Update(IReadOnlyList<int>): layer input. Patch37 wraps only the private no-arg Update.
        (EngineAssembly, EngineCallbacks, "EngineScreenManager_Update"),
        // ManagedScriptHolder.TickComponents: calls every ScriptComponentBehavior.OnTick override.
        (EngineAssembly, EngineCallbacks, "ManagedScriptHolder_TickComponents"),
        // ThumbnailCreatorView.OnThumbnailRenderComplete: portrait and item thumbnail callbacks.
        (EngineAssembly, EngineCallbacks, "ThumbnailCreatorView_OnThumbnailRenderComplete"),
        // RenderTargetComponent.OnPaintNeeded: raises PaintNeeded, the render function every
        // TableauView.AddTableau caller registers (CharacterTableau, ItemTableau, BannerTableau,
        // MapConversationTableau). It replaced BannerlordTableauManager_RequestCharacterTableauSetup,
        // whose RequestCallback nothing in v1.5.3 assigns (maintainer decision 2026-09-24, #650).
        (EngineAssembly, EngineCallbacks, "RenderTargetComponent_OnPaintNeeded"),

        // Mission combat callbacks with a traced path into TAOM code (maintainer decision
        // 2026-09-24, #650; the trace is in docs/features/crash-report.md). Several can arrive off
        // the main thread, so Native2ManagedBridge marks those captures for the reduced path.
        // These five reach Mission.RegisterBlow, then Agent.HandleBlow: Mission.OnAgentHit (TAOM
        // OnAgentHit and OnScoreHit overrides), Agent.Die and Agent.HandleBlowAux (TAOM patches).
        (CoreAssembly, CoreCallbacks, "Mission_MeleeHitCallback"),
        (CoreAssembly, CoreCallbacks, "Mission_MissileHitCallback"),
        (CoreAssembly, CoreCallbacks, "Mission_ChargeDamageCallback"),
        (CoreAssembly, CoreCallbacks, "Mission_FallDamageCallback"),
        (CoreAssembly, CoreCallbacks, "Mission_MissileAreaDamageCallback"),
        // Mission.OnAgentHitBlocked: Mission.OnAgentHit, as above.
        (CoreAssembly, CoreCallbacks, "Mission_OnAgentHitBlocked"),
        // MissionCombatMechanicsHelper.GetDefendCollisionResults: TaomCombatMechanicsModel.DecideCrushedThrough.
        (CoreAssembly, CoreCallbacks, "Mission_GetDefendCollisionResults"),
        // These three loop over every MissionBehavior, TAOM's included.
        (CoreAssembly, CoreCallbacks, "Mission_OnAgentRemoved"),
        (CoreAssembly, CoreCallbacks, "Mission_OnAgentDeleted"),
        (CoreAssembly, CoreCallbacks, "Mission_OnAgentShootMissile"),
    };

    // Resolves each target to its MethodInfo. A target whose assembly, type or method is absent is
    // added to `missing` as "Assembly/Type.Method" and skipped, so an engine rename costs one
    // warning line, never the whole attach.
    public static List<MethodInfo> Resolve(
        IEnumerable<(string AssemblyName, string TypeName, string MethodName)> targets,
        Func<string, Assembly?> findAssembly,
        ICollection<string> missing)
    {
        var resolved = new List<MethodInfo>();
        foreach (var (assemblyName, typeName, methodName) in targets)
        {
            MethodInfo? method = null;
            try
            {
                var type = findAssembly(assemblyName)?.GetType(typeName, throwOnError: false);
                method = type?.GetMethod(methodName, BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public);
            }
            catch (Exception)
            {
                method = null;
            }

            if (method != null)
                resolved.Add(method);
            else
                missing.Add($"{assemblyName}/{typeName}.{methodName}");
        }
        return resolved;
    }
}
