using System;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TAOM.Features.TrollBruteForce;

// The Brute Force action lives in LOTRLOME_Armory, which is UNVERSIONED: a reinstall drops it and nothing else in
// the repo would notice (#649). These tests pin the live data the C# relies on: the cave troll's Monster names the
// set the smash is bound in, the action is declared once and untyped (a synthetic RegisterBlow never runs the kick
// pipeline, so actt_kick buys nothing), and the set binds it exactly once to a clip package that exists. The set's
// body is generated by tools/bind_troll_action_set.py, so a lost binding is repaired by re-running it. Inconclusive
// where the Armory is not installed.

namespace TAOM.Tests.Features.TrollBruteForce;

[TestClass]
public class TrollBruteForceWiringTests
{
    private static string GameDir()
    {
        string? env = Environment.GetEnvironmentVariable("BANNERLORD_GAME_DIR");
        return string.IsNullOrWhiteSpace(env) ? @"E:\Steam\steamapps\common\Mount & Blade II Bannerlord" : env;
    }

    private static string Armory()
    {
        string armory = Path.Combine(GameDir(), "Modules", "LOTRLOME_Armory");
        if (!Directory.Exists(armory))
            Assert.Inconclusive("LOTRLOME_Armory not installed on this machine; the live data cannot be checked here.");
        return armory;
    }

    private static XDocument ModuleData(string file) => XDocument.Load(Path.Combine(Armory(), "ModuleData", file));

    [TestMethod]
    public void CaveTrollMonster_NamesTheSetTheSmashIsBoundIn()
    {
        var monster = ModuleData("monsters.xml").Descendants("Monster")
            .SingleOrDefault(m => (string?)m.Attribute("id") == TrollBruteForceConfig.CaveTrollMonsterId);

        Assert.IsNotNull(monster, "the cave_troll Monster is missing from the Armory's monsters.xml");
        Assert.AreEqual(TrollBruteForceConfig.ActionSetId, (string?)monster!.Attribute("action_set"));
    }

    [TestMethod]
    public void BruteForceAction_IsDeclaredOnce_Untyped()
    {
        var declared = ModuleData("action_types.xml").Descendants("action")
            .Where(a => (string?)a.Attribute("name") == TrollBruteForceConfig.ActionName)
            .ToList();

        Assert.AreEqual(1, declared.Count, $"{TrollBruteForceConfig.ActionName} must be declared exactly once in action_types.xml");
        Assert.IsNull(declared[0].Attribute("type"), $"{TrollBruteForceConfig.ActionName} must stay untyped");
    }

    [TestMethod]
    public void BruteForceAction_IsBoundOnceInTheCaveTrollSet_ToAClipThatExists()
    {
        var set = ModuleData("action_sets.xml").Descendants("action_set")
            .SingleOrDefault(s => (string?)s.Attribute("id") == TrollBruteForceConfig.ActionSetId);
        Assert.IsNotNull(set, $"{TrollBruteForceConfig.ActionSetId} is missing from the Armory's action_sets.xml");

        var bindings = set!.Elements("action")
            .Where(a => (string?)a.Attribute("type") == TrollBruteForceConfig.ActionName)
            .ToList();
        Assert.AreEqual(1, bindings.Count, $"{TrollBruteForceConfig.ActionName} must be bound exactly once in {TrollBruteForceConfig.ActionSetId}");

        string? clip = (string?)bindings[0].Attribute("animation");
        Assert.IsFalse(string.IsNullOrEmpty(clip), "the binding names no clip");
        string package = Path.Combine(Armory(), "Assets", "creature", "troll", "animations", clip + "_anm.tpac");
        Assert.IsTrue(File.Exists(package), $"{clip} has no clip package at {package}");
    }
}
