using System;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TAOM.Features.TrollBruteForce;

// The Brute Force action lives in LOTRLOME_Armory, which is UNVERSIONED: a reinstall drops it and nothing else in
// the repo would notice (#649). These tests pin the live data the C# relies on: each troll's Monster names the set
// the smash is bound in, the action is declared once and untyped (a synthetic RegisterBlow never runs the kick
// pipeline, so actt_kick buys nothing), and each set binds it exactly once to its own troll's clip package. The sets'
// bodies are generated by tools/bind_troll_action_set.py (cave troll) and tools/bind_hill_troll_action_set.py (hill
// troll), so a lost binding is repaired by re-running the matching one; `python tools/wire_hill_troll_race.py
// --check` covers the rest of the hill troll's race wiring. Inconclusive where the Armory is not installed.

namespace TAOM.Tests.Features.TrollBruteForce;

[TestClass]
[TestCategory("LiveInstall")]
public class TrollBruteForceWiringTests
{
    private static string GameDir()
    {
        string? env = Environment.GetEnvironmentVariable("BANNERLORD_GAME_DIR");
        return string.IsNullOrWhiteSpace(env) ? @"E:\Steam\steamapps\common\Mount & Blade II Bannerlord" : env;
    }

    private static string Armory()
    {
        string armory = Path.Combine(GameDir(), "Modules", "LOTRLOME_Armory");
        if (!Directory.Exists(armory))
            Assert.Inconclusive("LOTRLOME_Armory not installed on this machine; the live data cannot be checked here.");
        return armory;
    }

    private static XDocument ModuleData(string file) => XDocument.Load(Path.Combine(Armory(), "ModuleData", file));

    [TestMethod]
    public void EveryBruteForceMonster_NamesTheSetTheSmashIsBoundIn()
    {
        var monsters = ModuleData("monsters.xml").Descendants("Monster").ToList();
        foreach (var pair in TrollBruteForceConfig.ActionSetsByMonster)
        {
            var monster = monsters.SingleOrDefault(m => (string?)m.Attribute("id") == pair.Key);
            Assert.IsNotNull(monster, $"the {pair.Key} Monster is missing from the Armory's monsters.xml");
            Assert.AreEqual(pair.Value, (string?)monster!.Attribute("action_set"), $"{pair.Key} names another set");
        }
    }

    [TestMethod]
    public void CaveTrollMonster_KeepsTheHumanEyeHeight_SoItsSmashTuningHolds()
    {
        // Body size is AgentScale times eye height over TrollBruteForceConfig.ReferenceEyeHeight (2026-09-25). The
        // distances were tuned on the cave troll at scale 1.9 with the human eye height; a changed Monster would
        // silently rescale its smash.
        var caveTroll = ModuleData("monsters.xml").Descendants("Monster")
            .SingleOrDefault(m => (string?)m.Attribute("id") == TrollBruteForceConfig.CaveTrollMonsterId);
        Assert.IsNotNull(caveTroll, "the cave_troll Monster is missing from the Armory's monsters.xml");

        float eye = float.Parse((string?)caveTroll!.Attribute("standing_eye_height") ?? "0",
            System.Globalization.CultureInfo.InvariantCulture);
        Assert.AreEqual(TrollBruteForceConfig.ReferenceEyeHeight, eye, 0.001f);
    }

    [TestMethod]
    public void BruteForceAction_IsDeclaredOnce_Untyped()
    {
        var declared = ModuleData("action_types.xml").Descendants("action")
            .Where(a => (string?)a.Attribute("name") == TrollBruteForceConfig.ActionName)
            .ToList();

        Assert.AreEqual(1, declared.Count, $"{TrollBruteForceConfig.ActionName} must be declared exactly once in action_types.xml");
        Assert.IsNull(declared[0].Attribute("type"), $"{TrollBruteForceConfig.ActionName} must stay untyped");
    }

    [DataTestMethod]
    [DataRow("as_cave_troll_warrior", "anim_troll_")]
    [DataRow("as_hill_troll_warrior", "anim_hill_troll_")]   // bound by tools/bind_hill_troll_action_set.py EXTRA_BINDINGS
    public void BruteForceAction_IsBoundOnceInEachTrollSet_ToAClipThatExists(string setId, string clipPrefix)
    {
        var set = ModuleData("action_sets.xml").Descendants("action_set")
            .SingleOrDefault(s => (string?)s.Attribute("id") == setId);
        Assert.IsNotNull(set, $"{setId} is missing from the Armory's action_sets.xml");

        var bindings = set!.Elements("action")
            .Where(a => (string?)a.Attribute("type") == TrollBruteForceConfig.ActionName)
            .ToList();
        Assert.AreEqual(1, bindings.Count, $"{TrollBruteForceConfig.ActionName} must be bound exactly once in {setId}");

        string? clip = (string?)bindings[0].Attribute("animation");
        Assert.IsFalse(string.IsNullOrEmpty(clip), "the binding names no clip");
        StringAssert.StartsWith(clip, clipPrefix, $"{setId} must bind its own troll's clip, not the other troll's");
        // the cave troll's clips live under creature/troll, the hill troll's under Race Test/Mordor/Trolls
        var packages = Directory.GetFiles(Path.Combine(Armory(), "Assets"), clip + "_anm.tpac", SearchOption.AllDirectories);
        Assert.AreEqual(1, packages.Length, $"{clip} must have exactly one clip package under the Armory's Assets, found {packages.Length}");
    }
}
