<#
.SYNOPSIS
    Decompiles all Bannerlord .NET DLLs into organized folder structure using ilspycmd.

.DESCRIPTION
    Produces one folder per DLL, grouped by category (Campaign, Core, Engine, etc.)
    matching the layout previously used for E:\Decompiled_Bannerlord\.

.PARAMETER GameDir
    Bannerlord install root. Default: E:\Steam\steamapps\common\Mount & Blade II Bannerlord

.PARAMETER OutputDir
    Where to write decompiled source. Default: E:\Decompiled_Bannerlord

.PARAMETER DryRun
    List what would be decompiled without actually running ilspycmd.
#>
param(
    [string]$GameDir = "E:\Steam\steamapps\common\Mount & Blade II Bannerlord",
    [string]$OutputDir = "E:\Decompiled_Bannerlord",
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

# Verify ilspycmd is available
$ilspy = Get-Command ilspycmd -ErrorAction SilentlyContinue
if (-not $ilspy) {
    Write-Error "ilspycmd not found in PATH. Install with: dotnet tool install -g ilspycmd"
    exit 1
}
Write-Host "Using ilspycmd: $($ilspy.Source)" -ForegroundColor Cyan

# Verify game directory
$binDir = Join-Path $GameDir "bin\Win64_Shipping_Client"
if (-not (Test-Path $binDir)) {
    Write-Error "Game bin directory not found: $binDir"
    exit 1
}

# Read game version
$versionFile = Join-Path $binDir "Version.xml"
$gameVersion = "unknown"
if (Test-Path $versionFile) {
    [xml]$vxml = Get-Content $versionFile
    $gameVersion = $vxml.Version.Singleplayer.Value
}
Write-Host "Game version: $gameVersion" -ForegroundColor Cyan

# DLL source directories
$dllSources = @{
    "bin"       = $binDir
    "sandbox"   = Join-Path $GameDir "Modules\SandBox\bin\Win64_Shipping_Client"
    "storymode" = Join-Path $GameDir "Modules\StoryMode\bin\Win64_Shipping_Client"
    "native"    = Join-Path $GameDir "Modules\Native\bin\Win64_Shipping_Client"
}

# Category mapping: DLL base name (without .dll) -> category folder
# Order matters — first match wins for prefix-based rules
$categoryRules = [ordered]@{
    # Exact matches first (checked before prefix rules)
    "TaleWorlds.Core.ViewModelCollection"           = "UI"
    "TaleWorlds.Core"                               = "Core"
    "TaleWorlds.DotNet.AutoGenerated"               = "Engine"
    "TaleWorlds.DotNet"                             = "Core"
    "TaleWorlds.Library"                            = "Core"
    "TaleWorlds.LinQuick"                           = "Core"
    "TaleWorlds.Localization"                       = "Core"
    "TaleWorlds.ObjectSystem"                       = "Core"
    "TaleWorlds.SaveSystem"                         = "Core"
    "TaleWorlds.InputSystem"                        = "Engine"
    "TaleWorlds.NavigationSystem"                   = "Engine"
    "TaleWorlds.ScreenSystem"                       = "Engine"
    "TaleWorlds.PSAI"                               = "UI"
    "TaleWorlds.Network"                            = "Network"
    "TaleWorlds.PlayerServices"                     = "Network"
    "TaleWorlds.ServiceDiscovery.Client"             = "Network"
    "TaleWorlds.AchievementSystem"                  = "Platform"
    "TaleWorlds.ActivitySystem"                     = "Platform"
    "TaleWorlds.ModuleManager"                      = "Platform"
    "TaleWorlds.Starter.Library"                    = "Platform"
    # Prefix-based rules
    "TaleWorlds.CampaignSystem"                     = "Campaign"
    "TaleWorlds.MountAndBlade.Launcher"             = "Launcher"
    "TaleWorlds.MountAndBlade.Multiplayer"          = "Network"
    "TaleWorlds.MountAndBlade.Diamond"              = "MountAndBlade"
    "TaleWorlds.MountAndBlade.Helpers"              = "MountAndBlade"
    "TaleWorlds.MountAndBlade.ViewModelCollection"  = "MountAndBlade"
    "TaleWorlds.MountAndBlade.AutoGenerated"        = "MountAndBlade"
    "TaleWorlds.MountAndBlade"                      = "MountAndBlade"
    "TaleWorlds.Engine"                             = "Engine"
    "TaleWorlds.TwoDimension"                       = "Engine"
    "TaleWorlds.GauntletUI"                         = "UI"
    "TaleWorlds.Diamond"                            = "Network"
    "TaleWorlds.PlatformService"                    = "Platform"
    "SandBox"                                       = "Modules"
    "StoryMode"                                     = "Modules"
    # Third-party
    "Newtonsoft.Json"                               = "ThirdParty"
    "Steamworks.NET"                                = "ThirdParty"
    "jose-jwt"                                      = "ThirdParty"
    "GalaxyCSharp"                                  = "ThirdParty"
    "System.Management"                             = "ThirdParty"
    "System.Numerics.Vectors"                       = "ThirdParty"
}

# DLLs to skip (native/non-.NET)
$skipPatterns = @(
    "EOSSDK*", "Galaxy64*", "GalaxyCSharpGlue*",
    "GFSDK*", "GfeSDK*",
    "PhysX*",
    "fmod*",
    "grCore*", "grGranite*",
    "amd_ags*", "nvngx*",
    "mono-*", "MonoPosixHelper*",
    "dbgcore*", "dbghelp*", "msdia*", "symsrv*",
    "d3dcompiler*", "steam_api*", "StbSharp*"
)

function Get-Category([string]$dllName) {
    $baseName = [System.IO.Path]::GetFileNameWithoutExtension($dllName)
    foreach ($key in $categoryRules.Keys) {
        if ($baseName -eq $key -or $baseName.StartsWith("$key.")) {
            return $categoryRules[$key]
        }
    }
    return $null
}

function Should-Skip([string]$dllName) {
    $baseName = [System.IO.Path]::GetFileNameWithoutExtension($dllName)
    foreach ($pattern in $skipPatterns) {
        if ($baseName -like $pattern) { return $true }
    }
    return $false
}

# Collect all DLLs to process
$jobs = @()
foreach ($sourceKey in $dllSources.Keys) {
    $dir = $dllSources[$sourceKey]
    if (-not (Test-Path $dir)) {
        Write-Warning "DLL source not found, skipping: $dir"
        continue
    }

    $dlls = Get-ChildItem -Path $dir -Filter "*.dll" -File
    foreach ($dll in $dlls) {
        if (Should-Skip $dll.Name) { continue }

        $category = Get-Category $dll.Name

        # Native module DLLs that don't match main categories go to Native
        if (-not $category -and $sourceKey -eq "native") {
            $category = "Native"
        }

        if (-not $category) {
            Write-Warning "No category mapping for: $($dll.Name) (source: $sourceKey) - skipping"
            continue
        }

        $baseName = [System.IO.Path]::GetFileNameWithoutExtension($dll.Name)
        $outPath = Join-Path $OutputDir "$category\$baseName"

        $jobs += [PSCustomObject]@{
            DllPath  = $dll.FullName
            BaseName = $baseName
            Category = $category
            OutPath  = $outPath
            Source   = $sourceKey
        }
    }
}

# Deduplicate: same DLL in multiple sources, prefer bin then sandbox then storymode then native
$deduped = $jobs | Group-Object BaseName | ForEach-Object {
    $group = $_.Group
    if ($group.Count -eq 1) { $group[0] }
    else {
        $priority = @("bin", "sandbox", "storymode", "native")
        foreach ($p in $priority) {
            $match = $group | Where-Object { $_.Source -eq $p } | Select-Object -First 1
            if ($match) { $match; break }
        }
    }
}

Write-Host ""; Write-Host "DLLs to decompile: $($deduped.Count)" -ForegroundColor Green
Write-Host "Categories:" -ForegroundColor Green
$deduped | Group-Object Category | Sort-Object Name | ForEach-Object {
    Write-Host "  $($_.Name): $($_.Count) DLLs"
}

if ($DryRun) {
    Write-Host ""; Write-Host "[DRY RUN] Would decompile:" -ForegroundColor Yellow
    $deduped | Sort-Object Category, BaseName | ForEach-Object {
        Write-Host ("  {0}/{1}  from  {2}" -f $_.Category, $_.BaseName, $_.DllPath)
    }
    exit 0
}

# Create output directory
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

# Decompile each DLL
$succeeded = 0
$failed = @()
$totalFiles = 0
$sw = [System.Diagnostics.Stopwatch]::StartNew()

foreach ($job in $deduped | Sort-Object Category, BaseName) {
    $i = $deduped.IndexOf($job) + 1
    Write-Host "[$i/$($deduped.Count)] $($job.Category)/$($job.BaseName)" -ForegroundColor White -NoNewline

    New-Item -ItemType Directory -Path $job.OutPath -Force | Out-Null

    try {
        $output = & ilspycmd $job.DllPath -p -o $job.OutPath 2>&1
        $csFiles = (Get-ChildItem -Path $job.OutPath -Filter "*.cs" -Recurse -ErrorAction SilentlyContinue).Count
        $totalFiles += $csFiles
        $succeeded++
        Write-Host " -> $csFiles files" -ForegroundColor Green
    }
    catch {
        $failed += $job
        Write-Host " -> FAILED: $_" -ForegroundColor Red
    }
}

$sw.Stop()

# Write VERSION.txt
$versionContent = "Bannerlord Version: $gameVersion`r`n"
$versionContent += "Decompiled: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`r`n"
$versionContent += "Tool: ilspycmd $((ilspycmd --version 2>&1) -join ' ')`r`n"
$versionContent += "DLLs: $succeeded / $($deduped.Count)`r`n"
$versionContent += "Files: $totalFiles"
Set-Content -Path (Join-Path $OutputDir "VERSION.txt") -Value $versionContent

# Summary
Write-Host ""; Write-Host "========== SUMMARY ==========" -ForegroundColor Cyan
Write-Host "Version:    $gameVersion"
Write-Host "Output:     $OutputDir"
Write-Host "Succeeded:  $succeeded / $($deduped.Count)"
Write-Host "CS files:   $totalFiles"
Write-Host "Time:       $([math]::Round($sw.Elapsed.TotalMinutes, 1)) minutes"

if ($failed.Count -gt 0) {
    Write-Host ""; Write-Host "FAILED:" -ForegroundColor Red
    $failed | ForEach-Object { Write-Host "  $($_.BaseName) ($($_.DllPath))" -ForegroundColor Red }
}

Write-Host ""; Write-Host "Done." -ForegroundColor Green
