#!/usr/bin/env python3
"""Author each race's MISSING civilian action sets as thin base_set aliases.

Fixer for tools/audit_civilian_action_set_coverage.py. At settlement spawn the engine
GENERATES a townsfolk role set name `as_<race>[_female]_<suffix>`; if it does not exist
the lookup silently falls back to ONE default set, so every NPC of that role plays the
same idle (the "all elves do the same animation in every town" bug, plus the 3 prop-carry
sets every non-human race was missing).

For every SETTLEMENT race that lacks part of the human civilian family this tool emits a
one-line alias so the generated name resolves. base_set rule (by skeleton):

  * human-skeleton race  (root as_human_warrior, incl. elf/sauron which reference it
        directly and have no own family) -> base_set = as_human_<suffix>
        (correct role animation; elf/orc/uruk/... all share the human skeleton)
  * own-skeleton race    (e.g. dwarf, root as_dwarf_warrior)
        -> base_set = as_<race>_villager   (same skeleton, safe generic idle -- never
        cross-references a human-skeleton clip onto the dwarf rig, the 1.4.6 water-CTD class)

Thin self-closing aliases are the proven form: vanilla itself defines its female carry
sets exactly this way (`as_human_female_villager_carry_axe base_set="as_human_villager_carry_axe" />`).
Civilian lookups DO fall through base_set (unlike the facegen path, per the 2026-05-22 RCA).

The generated block is wrapped in TAOM-CIVILIAN-COVERAGE markers and inserted before the
closing </action_sets>. Idempotent (a re-run replaces the block), writes a .bak, --dry-run
default. Run against BOTH the live LOTRLOME action_sets.xml AND the tracked snapshot.
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from audit_civilian_action_set_coverage import (  # noqa: E402
    DEFAULT_LIVE, DEFAULT_NATIVE, OWN_SKELETON_RACES, SETTLEMENT_RACES,
    load, merge, reference_suffixes,
)

START = "\t<!-- TAOM-CIVILIAN-COVERAGE:START (generated by tools/generate_race_civilian_action_sets.py) -->"
END = "\t<!-- TAOM-CIVILIAN-COVERAGE:END -->"


def parse_sets_from_text(text: str) -> dict:
    """{id: {base, skel}} from action_sets XML text (comments ignored by ET)."""
    d: dict = {}
    try:
        root = ET.fromstring(text.encode("utf-8"))
    except ET.ParseError as exc:
        sys.exit(f"ERROR: target is not well-formed UTF-8 XML: {exc}")
    for s in root.findall("action_set"):
        sid = s.get("id")
        if not sid:
            continue
        rec = d.setdefault(sid, {"base": None, "skel": None})
        if s.get("base_set"):
            rec["base"] = s.get("base_set")
        if s.get("skeleton"):
            rec["skel"] = s.get("skeleton")
    return d


def strip_block(text: str) -> str:
    """Drop a previously-generated coverage block so a re-run does NOT count our own
    aliases as 'already present' (which would emit an empty block and delete the fix)."""
    return re.sub(re.escape(START) + r".*?" + re.escape(END) + r"[^\n]*\n?", "", text, flags=re.S)


def compute_aliases(native: dict, universe: dict):
    """Yield (race, id, base_set) alias tuples for every missing civilian set, per race."""
    male_ref, female_ref = reference_suffixes(native)
    out = []
    for race in SETTLEMENT_RACES:
        if race == "human":
            continue
        own_skeleton = race in OWN_SKELETON_RACES  # explicit; the only such race is dwarf

        def base_for(suffix: str, female: bool) -> str:
            if own_skeleton:
                # same-skeleton generic villager (dwarf); female villager if present, else male
                fem = f"as_{race}_female_villager"
                return fem if (female and fem in universe) else f"as_{race}_villager"
            return f"as_human_female_{suffix}" if female else f"as_human_{suffix}"

        for female, ref in ((False, male_ref), (True, female_ref)):
            for s in sorted(ref):
                sid = f"as_{race}_female_{s}" if female else f"as_{race}_{s}"
                if sid in universe:
                    continue
                base = base_for(s, female)
                if base == sid:
                    # own-skeleton race missing its OWN base villager -> can't self-alias; skip + warn
                    print(f"WARN: {sid} would self-reference (own-skeleton race missing its base "
                          f"villager) -- skipped; author as_{race}_villager first.")
                    continue
                out.append((race, sid, base))
    return out


def render(aliases, universe, nl: str):
    """Return (block_text, dangling) where dangling = [(id, base)] whose base_set is unknown."""
    lines = [START]
    dangling = []
    cur_race = None
    for race, sid, base in aliases:
        if race != cur_race:
            cur_race = race
            lines.append(f"\t<!-- {race} -->")
        if base not in universe:
            dangling.append((sid, base))
        lines.append(f'\t<action_set id="{sid}" base_set="{base}" />')
    lines.append(END)
    return nl.join(lines) + nl, dangling


def splice(text: str, block: str, nl: str) -> str:
    """Strip ALL prior coverage blocks (dedup, idempotent) then insert one before </action_sets>."""
    text = strip_block(text)
    close = text.rfind("</action_sets>")
    if close == -1:
        sys.exit("ERROR: no closing </action_sets> in target")
    ls = text.rfind(nl, 0, close)
    line_start = 0 if ls == -1 else ls + len(nl)
    return text[:line_start] + block + text[line_start:]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--native", default=DEFAULT_NATIVE, help="authoritative Native action_sets.xml (reference family)")
    ap.add_argument("--target", default=DEFAULT_LIVE, help="action_sets.xml to write the elf/race aliases into")
    ap.add_argument("--apply", action="store_true", help="write the change (default is dry-run)")
    args = ap.parse_args()

    native = load(args.native)
    if "as_human_villager" not in native:
        sys.exit(f"ERROR: --native {args.native} has no 'as_human_villager' -- wrong/renamed file? "
                 "The reference civilian family would be empty.")

    target_path = Path(args.target)
    try:
        raw = target_path.read_bytes()
    except OSError as exc:
        sys.exit(f"ERROR: cannot read target {target_path}: {exc}")
    bom = b"\xef\xbb\xbf"
    has_bom = raw.startswith(bom)
    try:
        text = (raw[3:] if has_bom else raw).decode("utf-8")
    except UnicodeDecodeError as exc:
        sys.exit(f"ERROR: target {target_path} is not UTF-8: {exc}")
    nl = "\r\n" if "\r\n" in text else "\n"

    # Merged engine view = Native + the target WITHOUT any prior coverage block, so our own
    # generated aliases never count as "already present" (keeps the generator idempotent).
    universe = merge(native, parse_sets_from_text(strip_block(text)))
    aliases = compute_aliases(native, universe)

    per_race: dict = {}
    for race, _, _ in aliases:
        per_race[race] = per_race.get(race, 0) + 1
    applied = START in text
    print(f"Civilian sets to author: {len(aliases)}"
          + (" (block already present -- idempotent re-apply)" if applied else " (NEW)"))
    for race, n in per_race.items():
        print(f"   {race:12s} {n}")
    if not aliases:
        print("Every settlement race already has the full civilian family -- nothing to write.")
        return

    block, dangling = render(aliases, universe, nl)
    if dangling:
        print(f"\nERROR: {len(dangling)} alias(es) reference a base_set NOT in the merged universe -- "
              "refusing to write broken XML:")
        for sid, base in dangling:
            print(f"   {sid} -> {base}")
        sys.exit(1)
    new_text = splice(text, block, nl)

    if not args.apply:
        print(f"\nDRY RUN ({target_path}). Re-run with --apply to write. First 12 lines of the block:")
        for ln in block.split(nl)[:12]:
            print("   ", ln)
        return

    backup = target_path.with_suffix(target_path.suffix + ".bak")
    shutil.copy2(target_path, backup)
    target_path.write_bytes((bom if has_bom else b"") + new_text.encode("utf-8"))
    print(f"\nWrote {len(aliases)} alias sets into {target_path}")
    print(f"Backup: {backup}")


if __name__ == "__main__":
    main()
