#!/usr/bin/env python3
"""Map a managed engine method (`[EngineMethod("x")]`) to its native implementation.

Managed Bannerlord calls the native engine through generated interfaces (`MBAPI.IMB*` for
MountAndBlade, `EngineApplicationInterface.I*` for Engine, `LibraryApplicationInterface.I*` for
DotNet): each `[EngineMethod("get_current_action_type")]` becomes a delegate that native code fills
at start-up. The shipping `TaleWorlds.Native.dll` keeps almost none of the names (on v1.5.3, 53 of
2,282 survive inside `IMono_<Class>::<name>` assert strings); the binding is an integer id. Each
AutoGenerated assembly declares the ids in a generated enum
(`ManagedCallbacks.ScriptingInterfaceObjects`, `enm_IMono_MBAgent_get_current_action_type = 69`)
and pairs every id with its C# interface and method in `SetFunctionPointer`'s switch. On the native
side one registration function per assembly passes each id with its implementation's address:
`lea rdx,[impl]; mov ecx,<id>; call [rbx+...]`, or from Engine id 817 on,
`lea r8,[impl]; mov edx,<id>; mov rcx,rbx; call <helper>`, in either order; the MountAndBlade and
Engine functions make their last registration in a tail call.

This module joins the two halves. The managed side comes from the installed AutoGenerated DLLs
beside the native one (`ilspycmd`, never the decompile dump); the native side from a capstone
sweep of the registration functions, found by instruction pattern, so a new build needs no
addresses. The joined map is cached per native binary. An id on one side only is reported, never
hidden: it means the map is incomplete for that binary, most likely because the sweep met an
instruction form it does not read, and answers for that assembly are unverified until it does.

Used by `tools/native_decompile.py` (`--engine-method`, and the reverse lookup on `--rva`).
Needs capstone. Background: docs/reference/bannerlord-engine-and-toolchain.md section 4.
"""
import bisect
import hashlib
import json
import os
import re
import struct
import subprocess
from collections import namedtuple
from pathlib import Path

ASSEMBLIES = ("MountAndBlade", "Engine", "DotNet")
ENUM_OWNER = "ManagedCallbacks.ScriptingInterfaceObjects"
MIN_SITES = 16  # the smallest registration function (DotNet) has 33 sites
FORMAT = 3  # 2: a superset function no longer wins; 3: nor stands in for a missing one

EngineMethod = namedtuple("EngineMethod", "assembly id iface method engine_name")
Resolved = namedtuple("Resolved", "assembly id iface method engine_name rva")


class EngineMapError(Exception):
    """The map cannot be built: a missing DLL or tool, or a decompile without the enum."""


# ---------------------------------------------------------------------------------------------
# Managed half
# ---------------------------------------------------------------------------------------------
_ENUM_BLOCK = re.compile(r"enum \w+GeneratedEnum\s*\{(.*?)\}", re.S)
_MEMBER = re.compile(r"^\s*(enm_IMono_\w+)(?:\s*=\s*(\d+))?\s*,?\s*$", re.M)
_CASE = re.compile(r"case \w+GeneratedEnum\.(enm_IMono_\w+):\s*ScriptingInterfaceOf(\w+)\.call_(\w+)Delegate")


def parse_generated_enum(text, assembly):
    """EngineMethods from a decompiled ScriptingInterfaceObjects. Values follow C# enum rules
    (explicit, else previous + 1). The C# interface and method come from the switch: engine
    names do not derive from C# names (`create_with_function` is `CreateWithDelegate`)."""
    block = _ENUM_BLOCK.search(text)
    if block is None:
        raise EngineMapError(f"no generated enum in the {assembly} decompile")
    pairing = {m.group(1): (m.group(2), m.group(3)) for m in _CASE.finditer(text)}
    methods, value = [], -1
    for m in _MEMBER.finditer(block.group(1)):
        member = m.group(1)
        value = int(m.group(2)) if m.group(2) is not None else value + 1
        iface, method = pairing.get(member, (None, None))
        rest = member[len("enm_IMono_"):]
        prefix = f"{iface[1:]}_" if iface else None
        name = rest[len(prefix):] if prefix and rest.startswith(prefix) else rest
        methods.append(EngineMethod(assembly, value, iface, method, name))
    return methods


def decompile_enum_owner(managed_dll):
    try:
        run = subprocess.run(["ilspycmd", str(managed_dll), "-t", ENUM_OWNER],
                             capture_output=True, text=True, timeout=300)
    except FileNotFoundError:
        raise EngineMapError("ilspycmd is not on PATH (dotnet tool install -g ilspycmd)") from None
    except subprocess.TimeoutExpired:
        raise EngineMapError(f"ilspycmd timed out decompiling {managed_dll}") from None
    if run.returncode != 0 or "GeneratedEnum" not in run.stdout:
        raise EngineMapError(f"ilspycmd could not decompile {ENUM_OWNER} from {managed_dll}")
    return run.stdout


# ---------------------------------------------------------------------------------------------
# Native half
# ---------------------------------------------------------------------------------------------
_FAMILY = {**{r: "c" for r in ("rcx", "ecx", "cx", "cl", "ch")},
           **{r: "d" for r in ("rdx", "edx", "dx", "dl", "dh")},
           **{r: "8" for r in ("r8", "r8d", "r8w", "r8b")}}
_LEA_RIP = re.compile(r"^(\w+), \[rip ([+-]) (0x[0-9a-f]+|\d+)\]$")
_MOV_IMM = re.compile(r"^(ecx|edx), (0x[0-9a-f]+|\d+)$")
_NO_WRITE = {"test", "cmp", "push", "nop"}


def registration_sites(code, base_rva):
    """[(id, implementation rva)] in order, from a linear sweep of one registration function.

    Tracks the three argument registers: an id in ecx with the pointer in rdx, or an id in edx
    with the pointer in r8. A call or jump (tail calls included) consumes them; any other write
    to one of them clears it."""
    try:
        from capstone import CS_ARCH_X86, CS_MODE_64, Cs
    except ImportError:
        raise EngineMapError("capstone is not installed for this Python (pip install capstone)") from None

    state, sites = {}, []
    for ins in Cs(CS_ARCH_X86, CS_MODE_64).disasm(code, base_rva):
        mnem, ops = ins.mnemonic, ins.op_str
        if mnem in ("call", "jmp"):
            c, d, r8 = state.get("c"), state.get("d"), state.get("8")
            if c and c[0] == "imm" and d and d[0] == "ptr":
                sites.append((c[1], d[1]))
            elif d and d[0] == "imm" and r8 and r8[0] == "ptr":
                sites.append((d[1], r8[1]))
            state.clear()
            continue
        if mnem.startswith("j"):
            state.clear()
            continue
        lea = _LEA_RIP.match(ops) if mnem == "lea" else None
        imm = _MOV_IMM.match(ops) if mnem == "mov" else None
        if lea and lea.group(1) in _FAMILY:
            disp = int(lea.group(3), 0)
            state[_FAMILY[lea.group(1)]] = ("ptr", ins.address + ins.size + (disp if lea.group(2) == "+" else -disp))
        elif imm:
            state[_FAMILY[imm.group(1)]] = ("imm", int(imm.group(2), 0))
        elif mnem == "xor" and ops in ("ecx, ecx", "edx, edx"):
            state[_FAMILY[ops[:3]]] = ("imm", 0)
        elif mnem not in _NO_WRITE:
            fam = _FAMILY.get(ops.split(",")[0].strip())
            if fam:
                state.pop(fam, None)
    return sites


_CANDIDATE = re.compile(rb"(?:\x48\x8D\x15|\x4C\x8D\x05)....(?:\xB9|\xBA|\x33\xC9|\x33\xD2|\x48\x8B\xCB)", re.S)


def scan_registrations(text, text_rva, pdata, min_sites=MIN_SITES):
    """{function rva: {id: implementation rva}} for every function registering >= min_sites.
    A byte pattern picks the candidate functions; the precise sweep decides."""
    starts = [s for s, _ in pdata]
    hits = {}
    for m in _CANDIDATE.finditer(text):
        i = bisect.bisect_right(starts, text_rva + m.start()) - 1
        if i >= 0 and text_rva + m.start() < pdata[i][1]:
            hits[i] = hits.get(i, 0) + 1
    found = {}
    for i, n in hits.items():
        if n < min_sites:
            continue
        start, end = pdata[i]
        sites = registration_sites(text[start - text_rva:end - text_rva], start)
        if len(sites) >= min_sites:
            found[start] = dict(sites)
    return found


def scan_dll(dll):
    import native_crash_triage as nct

    pe = nct.Pe(str(dll))
    _name, vaddr, _vsize, roff, rsize = pe.text
    po, psz = pe.pdata[3], pe.pdata[4]
    pdata = sorted(struct.unpack_from("<II", pe.d, po + i) for i in range(0, psz - 11, 12))
    return scan_registrations(pe.d[roff:roff + rsize], vaddr, pdata)


# ---------------------------------------------------------------------------------------------
# The join
# ---------------------------------------------------------------------------------------------
def assign(functions, methods):
    """Pair each assembly with the registration function whose ids differ least from its own;
    resolve. Returns (resolved, problems): any id on one side only is a problem, never dropped.

    Fewest one-sided ids, not most shared: Engine's function holds every MountAndBlade id, so
    ranking by shared ids hands MountAndBlade to Engine's function as soon as one MountAndBlade
    site is missed, and about 1,400 methods then resolve wrong with exit 0. A candidate must
    share at least half of both sides' ids, and the closest pairings across all assemblies claim
    their functions first, so a superset function cannot stand in for an assembly whose own
    function was not found, whatever the two assemblies' sizes."""
    expected = {a: {m.id: m for m in methods if m.assembly == a} for a in ASSEMBLIES}
    problems = [f"{a}: no managed ids parsed from its generated enum" for a in ASSEMBLIES if not expected[a]]
    pairs = sorted((len(exp.keys() ^ ids.keys()), ASSEMBLIES.index(a), fn)
                   for a, exp in expected.items() if exp
                   for fn, ids in functions.items()
                   if 2 * len(exp.keys() & ids.keys()) >= max(len(exp), len(ids)))
    chosen, taken = {}, set()
    for _, index, fn in pairs:
        if ASSEMBLIES[index] not in chosen and fn not in taken:
            chosen[ASSEMBLIES[index]] = fn
            taken.add(fn)
    resolved = []
    for assembly in ASSEMBLIES:
        if not expected[assembly]:
            continue
        if assembly not in chosen:
            problems.append(f"{assembly}: no native registration function matches its "
                            f"{len(expected[assembly])} managed ids")
            continue
        fn = chosen[assembly]
        expected_ids = expected[assembly]
        native = functions[fn]
        for ident in sorted(expected_ids.keys() & native.keys()):
            resolved.append(Resolved(*expected_ids[ident], native[ident]))
        missing = sorted(expected_ids.keys() - native.keys())
        extra = sorted(native.keys() - expected_ids.keys())
        if missing:
            problems.append(f"{assembly}: {len(missing)} managed id(s) not registered natively in "
                            f"0x{fn:X}: {missing[:8]}")
        if extra:
            problems.append(f"{assembly}: {len(extra)} native id(s) in 0x{fn:X} unknown to the "
                            f"managed enum: {extra[:8]}")
    return resolved, problems


class EngineMethodMap:
    def __init__(self, methods, problems=()):
        self.methods = list(methods)
        self.problems = list(problems)

    def lookup(self, query):
        """Accepts get_current_action_type, GetCurrentActionType, IMBAgent.GetCurrentActionType,
        MBAgent.get_current_action_type, a namespace-qualified interface
        (MBAPI.IMBAgent.X, TaleWorlds.MountAndBlade.IMBAgent.X), the enum member
        (enm_IMono_MBAgent_get_current_action_type) and the native assert form
        (IMono_MBAgent::get_current_action_type)."""
        q = query.strip()
        if q.startswith("enm_IMono_"):
            rest = q[len("enm_IMono_"):]
            return sorted((r for r in self.methods if rest in (r.engine_name, f"{(r.iface or ' ')[1:]}_{r.engine_name}")),
                          key=lambda r: (r.assembly, r.iface or "", r.id))
        if q.startswith("IMono_") and "::" in q:
            q = q[len("IMono_"):].replace("::", ".")
        iface, _, name = q.rpartition(".")
        iface = iface.rpartition(".")[2].replace("ScriptingInterfaceOf", "")

        def hit(r, fold):
            f = str.lower if fold else (lambda s: s)
            if iface and not (r.iface and f(iface) in (f(r.iface), f(r.iface[1:]))):
                return False
            return f(name) in (f(r.engine_name), f(r.method or ""))

        found = [r for r in self.methods if hit(r, False)] or [r for r in self.methods if hit(r, True)]
        return sorted(found, key=lambda r: (r.assembly, r.iface or "", r.id))

    def suggest(self, query, limit=8):
        core = query.rpartition(".")[2].replace("_", "").lower()
        out = []
        for r in self.methods:
            if core and core in (r.engine_name + (r.method or "")).replace("_", "").lower():
                out.append(f"{r.iface}.{r.method} ({r.engine_name})" if r.method else r.engine_name)
        return out[:limit]

    def by_rva(self, rva):
        return [r for r in self.methods if r.rva == rva]


def _sha16(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()[:16]


def load_or_build(dll, cache_dir, key, decompile=decompile_enum_owner, scan=scan_dll):
    """The map for this native binary, from `<cache_dir>/<key>.engine-methods.json` when the
    native key and every managed DLL hash still match, else built and cached."""
    dll = Path(dll)
    managed = {a: dll.parent / f"TaleWorlds.{a}.AutoGenerated.dll" for a in ASSEMBLIES}
    absent = [p.name for p in managed.values() if not p.is_file()]
    if absent:
        raise EngineMapError(f"{', '.join(absent)} not found beside {dll}; the engine-method map "
                             "needs the managed AutoGenerated DLLs of the same build")
    hashes = {a: _sha16(p) for a, p in managed.items()}
    cache = Path(cache_dir) / f"{key}.engine-methods.json"
    try:
        data = json.loads(cache.read_text(encoding="utf-8"))
        if data["format"] == FORMAT and data["native"] == key and data["managed"] == hashes:
            return EngineMethodMap([Resolved(*row) for row in data["methods"]], data["problems"])
    except (OSError, ValueError, KeyError, TypeError):
        pass  # absent, cut short or another shape: rebuild
    methods = []
    for assembly, path in managed.items():
        methods += parse_generated_enum(decompile(path), assembly)
    resolved, problems = assign(scan(dll), methods)
    if not problems:  # an incomplete map is rebuilt every run, so a sweep fix takes effect at once
        cache.parent.mkdir(parents=True, exist_ok=True)
        partial = cache.with_suffix(".tmp")
        partial.write_text(json.dumps({"format": FORMAT, "native": key, "managed": hashes,
                                       "problems": problems, "methods": [list(r) for r in resolved]}),
                           encoding="utf-8")
        os.replace(partial, cache)  # a killed run leaves the old cache or none, never half of one
    return EngineMethodMap(resolved, problems)
