using System.Collections.Generic;

namespace TAOM.Features.TroopProgression;

// Volunteer recruitment pool for Arthedain, the North-kingdom of Arvedui's line (troops generated by
// tools/generate_arthedain_troops.py). The data half of VolunteerRecruitmentService, registered by
// the static ctor in the core file. Lookup priority: conditional > settlement > clan > culture
// (troops.md).
public partial class VolunteerRecruitmentService
{
    private static void InitializeArthedainCulture()
    {
        // Two roots reach the whole tree: the Levy heads the Fornost infantry line, and the Dunadan
        // Youth splits into the Rangers, the Citadel guard and the short cavalry branch. Weighted
        // heavily to the levy: Arthedain's villages are few and poor, and a Dunadan of the old blood
        // is the exception among its volunteers.
        CultureMap["arthedain"] = new List<VolunteerChance>
        {
            new VolunteerChance("arthedain_levy", 6),
            new VolunteerChance("arthedain_dunadan_youth", 2)
        };
    }
}
